<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Активность',
    'Actions' => 'Действия',
    'Add' => 'Добавить',
    'Add device' => 'Добавить устройство',
    'Count row' => 'Количество строк',
    'Create' => 'Добавить',
    'Created' => 'Создан',
    'Creating' => 'Создается',
    'Created At' => 'Добавлено',
    'Create a segment by the specified parameters' => 'Создать сегмент по заданным параметрам',
    'Delete' => 'Удалить',
    'Devices' => 'Устройства',
    'Detailed information' => 'Подробная информация',
    'Download' => 'Скачать',
    'Error' => 'Ошибка',
    'The start date' => 'Начальная дата',
    'The end date' => 'Конечная дата',
    'The start date To' => 'Начальная дата До',
    'The end date To' => 'Конечная дата До',
    'Information from the site' => 'Информация из платформы',
    'Platform Id' => 'ID в площадке',
    'Segment title' => 'Название сегмента',
    'Status' => 'Статус',
    'Title' => 'Название',
    'Total items' => 'Всего элементов',
    'Enable interval' => 'Включить интервал',
    'View' => 'Просмотр',
    'View data for all time' => 'Просмотр данных за все время',
    'Video' => 'Ролик',
    
    
    'From' => 'С',
    'To' => 'По',
    'Count' => 'Количество повторов',
    'Last request' => 'Последнее обращение',
    'Login' => 'Войти',
    'Logout' => 'Выход',
    'Number of entries for the current day' => 'Количество записей за текущий день',
    'Username' => 'Имя пользователя',
    'Password' => 'Пароль',
    'Remember' => 'Запомнить',
    'Accumulated contacts' => 'Накопленные контакты',
    'This name has already been taken' => 'Это имя уже существует',
    'Unique name device' => 'Уникальное имя устройства',
    'Update device' => 'Изменить устройство',
    'Upload {entity}' => 'Загрузка {entity}',
    'Uploaded {entity}' => 'Загруженные {entity}',
    'View {entity}' => 'Просмотр {entity}',
    'Select {single}' => 'Выберите {single}',
    '{Entity} added successfully' => '{Entity} успешно добавлен(ы)',
    'Nothing found. Check the search criteria.' => 'Ничего не найдено. Проверьте критерии поиска.',
    'Playlist' => 'Плейлист',
    'Datas' => 'Данные',
    'data' => 'данных',
    'file' => 'файл',
    'files' => 'файлы',
    'playlist' => 'плейлиста',
    'playlists' => 'плейлист',
    'videos' => 'ролики',
    'devices' => 'устройства',
];
